# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
  publish = "build/"


  command = "npm run build"

[[redirects]]
  from = "https://chango666.netlify.app/"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "https://chango666.netlify.app/"
  to = "/public/manifest.json"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"











