[[redirects]]
  from = "/pathx"
  to = "http://red666.somee.com/WeatherForecast"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"